### ISSUE TITLE
Not working on Character menu or select screen.

### ISSUE THREAD

**Issue by ghost** [Ottermandias/Glamourer#22]
Possibly already known, but the custom design doesn't show on the character menu nor the character select screen.

I don't know if it's planned to be added or not, but if it is, would it be possible to change other related information? Like the info on the character select screen, that shows your race, Or when an NPC mentions your race. (Although I would guess that's way harder)
This is just extra though, it's the subject of this issue that is most jarring.

By the way, thank you for this plugin! I've been trying to get a bunch of friends into FFXIV recently, and being able to choose any race is surely going to be a plus for them.

PS.: Would it be possible to add custom animations? Last time I checked, the resource for this mentions that changing basic animations (like walking) was dangerous. But since this plugin changes that, I would guess it's maybe implemented differently and not as dangerous. I mostly want this so Hrothgars aren't hunchbacks.

**Comment by Ottermandias** [comment]
It is not possible to easily redraw those actors, so this can't be changed.
Everything else you request is out of scope for glamourer, too, sorry.
