### ISSUE TITLE
About GAIA NPC 

### ISSUE THREAD

**Issue by Etupa** [Ottermandias/Glamourer#33]
Hello, dunno if it's a problem or if it works as intended.

Gaia NPC from Eden raid of ShB is actually shown as a MONSTER... and the change to npc function makes a male hyur from her ? don't get it.

Well, if it needs to be completed by screen or anything else, let me know.

Thanks for this truely amazing plug anyway.

**Comment by RaynaKannon** [comment]
IIRC Gaia doesn't have an NPC model since her body and head is specific to her

**Comment by Etupa** [comment]
So, actually it works as intended ;)

Thx Rayana
