### ISSUE TITLE
Feature Request: Don't Overwrite Weapon option

### ISSUE THREAD

**Issue by SashaFFXIV** [Ottermandias/Glamourer#34]
Overwriting the weapon breaks job animations if it's not the correct weapon for that job, forcing you to manually change the weapon every time you switch jobs. If there was an option to not overwrite the weapon you wouldn't have to do that.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/173227329-77a19f1b-948e-4969-9c28-797ddabd1a1e.png)
?

**Comment by SashaFFXIV** [comment]
Oh I'm fucking stupid, lol. For some reason I thought those were for the dyes.
