### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by Lockehart** [Ottermandias/Glamourer#44]
With the 1.0.4 update which auto-installed it removed itself from my installed plugin list and every attempt to reinstall from the All Plugins list gives an error.

**Comment by Ottermandias** [comment]
Post your %appdata%\XIVLauncher\dalamud.log  log.

**Comment by Lockehart** [comment]
[dalamud.log](https://github.com/Ottermandias/Glamourer/files/9033414/dalamud.log)

**Comment by Ottermandias** [comment]
```
2022-07-02 13:56:37.022 -04:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: READ THIS
======== Could not obtain the human.cmp file which is necessary for color sets.
======== This usually indicates an error with your index files caused by TexTools modifications.
======== If you have used TexTools before, you will probably need to start over in it to use Glamourer.
 ---> System.NotImplementedException: File Type 2338145254 is not implemented.
 ```
 Your clients indices are corrupted by TexTools. You need to at least start over in TexTools, preferably use the Quicklaunchers Repair function.

**Comment by Lockehart** [comment]
That did the trick!  Thank you so much :D
