### ISSUE TITLE
Suggestion: Fixed designs for NPC/Monsters

### ISSUE THREAD

**Issue by Dajova** [Ottermandias/Glamourer#46]
Title says it, support for NPC/Monster-specific fixed designs and/or macros. Hopefully one that can bypass the numbers:
![image](https://i.imgur.com/sdkoq03.png)
(or at least have a checkbox if you want to apply to all with same name).

**Comment by Ottermandias** [comment]
No.

**Comment by Dajova** [comment]
Ok, i saw [here](https://github.com/Ottermandias/Glamourer/issues/11) that it would mess with the game to use fixed design, that i can accept. But what about the other thing, by using macros? Surely that would work?
