### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by si811** [Ottermandias/Glamourer#48]
followed the instructions to Copy https://raw.githubusercontent.com/Ottermandias/Glamourer/main/repo.json to your custom repos in dalamud but it just states that download has failed every time I log into the game.

**Comment by unknownuserxv** [comment]
I’m having the exact same problem. It fails to download.

**Comment by Ottermandias** [comment]
What exactly fails to download?
Are you sure that it does not fail to install instead?
Please post error messages or screenshots.
Also, very likely your client is messed up by TT.

**Comment by si811** [comment]
[https://imgur.com/a/Q4IhOcq](url)

**Comment by si811** [comment]
realised the issue as soon as I uploaded the screenshot, I was missing an n at the end.
