### ISSUE TITLE
[Feature Request] Manual Save Button

### ISSUE THREAD

**Issue by Deckerz** [Ottermandias/Glamourer#49]
if you make loads of changes but FF crashes on exit they dont save. A manual save button would fix this issue.

**Comment by jayajr** [comment]
Would also love this feature! Is there a way to ensure our stuff saves now as a workaround? Maybe only 2 or 3 edits at a time and close?

**Comment by Ottermandias** [comment]
Everything saves on any change. It has nothing to do with XIV crashing. It just has some bug I don't care about since I'm reworking the entire plugin.
