### ISSUE TITLE
Having separate fixed designs for changing character and for changing gear active does not work properly across areas.

### ISSUE THREAD

**Issue by Otaku-2** [Ottermandias/Glamourer#51]
If you have a design that changes character customization and not equipment, and one that changes character equipment and not customization, when an area change occurs, Glamourer only takes the bottom-most design and applies it to the character.

The expected outcome would be to apply both designs without a problem. The problem is possibly that it's attempting to apply both at the same time, so it only puts into effect the last one? idk

**Comment by Ottermandias** [comment]
No, the expected outcome is exactly what's happening. It will only apply one fixed design in any given situation.
