### ISSUE TITLE
[Feature Request] Voice Options

### ISSUE THREAD

**Issue by Takaria** [Ottermandias/Glamourer#57]
Hello! I was wondering if it'd be possible to add options for voices under "Character Customization"? I see most other options for configurations and would greatly appreciate being able to do it from within Glamourer instead of Anamnesis manually each time.

Thank you so much for your consideration!

**Comment by Ottermandias** [comment]
No, voices are not part of the customize array used to manipulate things. After the rework, Glamourer will not manipulate your game object anymore, as that is unsafe, and only touch the draw object, which has no concept of a voice.
