### ISSUE TITLE
Safe to use in instances/duties?

### ISSUE THREAD

**Issue by sofiexe** [Ottermandias/Glamourer#59]
Been skeptical and wondering if this sends data to the server when you change your appearance.

Unsure if writing your appearance sends data to the server when in a duty or instance.

**Comment by Ottermandias** [comment]
It does not. You should avoid having it on when visiting the aesthetician until the rework is done, but otherwise it should not cause problems.
Oh, and probably better to avoid converting enemies to player characters, that might fuck animation shit.
