### ISSUE TITLE
[Feature Request] Fixed Design link to Collection in Penumbra

### ISSUE THREAD

**Issue by Slashic** [Ottermandias/Glamourer#67]
It would be nice to be able to link a Fixed Design in Glamourer to a Collection in Penumbra.
Tbh i don't know which end should trigger the other (maybe both why not) but that would be a cool feature removing the hassle to manually match a Fixed Design with a Penumbra collection for the glamour to be correctly applied.

One solution could also be to have text commands for this (for both Glamourer and Penumbra) so we can organise them in macros.

**Comment by Ottermandias** [comment]
Not gonna happen soon.
