### ISSUE TITLE
Feature Request: Fitting Room preview

### ISSUE THREAD

**Issue by gynryiie** [Ottermandias/Glamourer#9]
It might not be in the scope of the plugin's intended use, but would like to have a feature to temporarily apply the glamour you have set in your fitting room window while it's open.

**Comment by Ottermandias** [comment]
I can't redraw the fitting room actor as it just gets put in the world instead of the fitting room window. I hadn't figured out what causes this or how to fix it when I researched it in Penumbra, so it's not possible at the moment.
